### PR TITLE
Refactor some codes and fix some bugs

### PR DESCRIPTION
**Pull request by hanchaa**
This revision includes:

- Refactor some codes
   - Object::GetTile method: Method was deleted because it was never used
   - Map::CanLurkerAttackThisMove method: Name of method was changed to "CanLurkerAttack"
   - Map::CanLurkerAttackNextMove method: Method was deleted because it was never used
   - Map files: Removed second layer flag from map files because every map has second layer
   - Game::CanMove method: Changed the logic of checking endpoint -> Return MoveState::ENDPOINT if position's first layer object is empty and second layer is endpoint. Also changed Object::HasType method.

* Fix some bugs
   * Undead didn't die if it goes onto spike

### CODE REVIEW

**Comment by hyp3rflow** [comment]
LGTM!

**Review by hyp3rflow — APPROVED** [review]
LGTM!

**Review by utilForever — CHANGES_REQUESTED** [review]
LGTM. However, you should change Python test code, too.

**Review by mung3477 — APPROVED** [review]
Lots of things were changed. LGTM!

**Review by mung3477 — APPROVED** [review]
LGTM.

**Review by hyp3rflow — APPROVED** [review]
LGTM

**Review by utilForever — APPROVED** [review]
LGTM now. Good to go~ 😎

**Pull request merged**
